# Generated by Django 6.0.1 on 2026-02-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view", "Can view user"),
                    ("can_create", "Can create user"),
                    ("can_edit", "Can edit user"),
                    ("can_delete", "Can delete user"),
                ]
            },
        ),
    ]
